### PR TITLE
Conditionally pass an int to pluralize/singularize

### PR DESCRIPTION
**Pull request by timkelty**
Makes these inflector methods way more useful, especially in a templating context, e.g.:

```
{{ cart.totalQty }} {{ 'item'|pluralize(cart.totalQty) }} in your cart
```

### CODE REVIEW

**Comment by khalwat** [comment]
Ah very nice, thanks! Any chance you can switch it to be against the `develop` branch tho @timkelty ?

**Comment by timkelty** [comment]
oh sure.

**Comment by khalwat** [comment]
looks like somehow you just made a PR for the last commit I pushed? @timkelty 

btw, if there's some way that _I_ can switch the PR to the `develop` branch, let me know. I'm just unaware of whether I'm able to do that or not.

**Comment by khalwat** [comment]
Ugh, never mind.

**Comment by timkelty** [comment]
I just rebased off `develop` and switched base branch to `develop` for the PR

**Comment by khalwat** [comment]
I'm gonna do something similar with `singularize` I think

**Comment by khalwat** [comment]
...except you already did.

Fine!

I'll just update the docs heh

**Pull request merged**
